{
 "title": "CRDB Console: Changefeeds by Test Run and Name",
 "tags": [ "crdb-console-run-name" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "test_run_id",
    "label": "Test Run ID",
    "query": {
     "query": "label_values(sys_uptime{job=\"cockroachdb\"},test_run_id)"
    }
   },
   {
    "name": "test_name",
    "label": "Test",
    "query": {
     "query": "label_values(sys_uptime{job=\"cockroachdb\",test_run_id=~\"$test_run_id\"},test_name)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(sys_uptime{job=\"cockroachdb\",test_run_id=~\"$test_run_id\", test_name=~\"$test_name\"},instance)"
    }
   },
   { "name": "rate_interval", "label": "Rate Interval", "query": "30s,1m,5m,10m,30m,1h,6h,12h,1d" }
  ]
 },
 "panels": [
  {
   "title": "Max Changefeed Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ns", "label": "time" }
   ],
   "targets": [
    {
     "expr": "sum(rate(changefeed_max_behind_nanos{job=\"cockroachdb\",test_run_id=~\"$test_run_id\", test_name=~\"$test_name\",instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Max Changefeed Latency"
    }
   ]
  },
  {
   "title": "Sink Byte Traffic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(changefeed_emitted_bytes{job=\"cockroachdb\",test_run_id=~\"$test_run_id\", test_name=~\"$test_name\",instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Emitted Bytes"
    }
   ]
  },
  {
   "title": "Sink Counts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "actions" }
   ],
   "targets": [
    {
     "expr": "sum(rate(changefeed_emitted_messages{job=\"cockroachdb\",test_run_id=~\"$test_run_id\", test_name=~\"$test_name\",instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Messages"
    },
    {
     "expr": "sum(rate(changefeed_flushes{job=\"cockroachdb\",test_run_id=~\"$test_run_id\", test_name=~\"$test_name\",instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Flushes"
    }
   ]
  },
  {
   "title": "Sink Timings",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "ns", "label": "time" }
   ],
   "targets": [
    {
     "expr": "sum(rate(changefeed_emitted_messages{job=\"cockroachdb\",test_run_id=~\"$test_run_id\", test_name=~\"$test_name\",instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Message Emit Time"
    },
    {
     "expr": "sum(rate(changefeed_flush_nanos{job=\"cockroachdb\",test_run_id=~\"$test_run_id\", test_name=~\"$test_name\",instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Flush Time"
    }
   ]
  },
  {
   "title": "Changefeed Restarts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short", "label": "actions" }
   ],
   "targets": [
    {
     "expr": "sum(rate(jobs_changefeed_resume_retry_error{job=\"cockroachdb\",test_run_id=~\"$test_run_id\", test_name=~\"$test_name\",instance=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Retryable Errors"
    }
   ]
  },
  {
   "title": "Cluster Checkpoint Lag",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "ns", "label": "time" }
   ],
   "targets": [
    {
     "expr": "changefeed_checkpoint_lag{job=\"cockroachdb\",test_run_id=~\"$test_run_id\", test_name=~\"$test_name\",instance=~\"$node\"}",
     "legendFormat": "job_id={{job_id}}"
    }
   ]
  }
 ]
}